sudo: required
 
services:
  - docker
 
dist: trusty
 
language: python
python:
  - '3.6'
 
install:
  - python

script:
  - python test
  - python run

deploy:
  provider: pages
  skip-cleanup: true
  gitup-tocken: $GITHUB_TOKEN
  on:
    branch: master 